  
language: python

python: "3.6"

addons:
  postgresql: "9.4"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c 'create database aquacres;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script: coverage run --source='.' manage.py test && coverage report

after_success: coveralls
